name: workflow.yml
on:
  push:
    tags:
      - '*-build.*'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: msi
            artifact_name: msi-installer
            path: build/compose/binaries/main/msi/*.msi
          - os: macos-latest
            target: dmg
            artifact_name: dmg-installer
            path: build/compose/binaries/main/dmg/*.dmg

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build ${{ matrix.target }}
        run: ./gradlew package${{ matrix.target | capitalize }}

      - name: Upload ${{ matrix.target }} artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.path }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: ${{ matrix.path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
