name: Build and Release Desktop Distributions

on:
  push:
    tags:
      - '*-build.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout desktop repo
        uses: actions/checkout@v4
        with:
          path: Medal-app-desktop

      - name: Checkout medal-core repo
        uses: actions/checkout@v4
        with:
          repository: SMFDrummer/Medal-core
          path: Medal-core

      - name: Dump workspace layout
        run: ls -R .

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./Medal-app-desktop/gradlew
        if: runner.os != 'Windows'

      - name: Build native distributions
        working-directory: Medal-app-desktop
        run: ./gradlew packageDistributionForCurrentOS

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: distributions-${{ matrix.os }}
          path: |
            Medal-app-desktop/build/compose/binaries/**/*.msi
            Medal-app-desktop/build/compose/binaries/**/*.exe
            Medal-app-desktop/build/compose/binaries/**/*.deb
            Medal-app-desktop/build/compose/binaries/**/*.dmg

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/**/**/*.msi
            artifacts/**/**/*.exe
            artifacts/**/**/*.deb
            artifacts/**/**/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
