name: Build and Release Desktop Distributions

on:
  push:
    tags:
      - '*-build.*'

jobs:
  build:
    name: Build Desktop Distributions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew
        if: runner.os != 'Windows'

      - name: Build native distributions
        run: ./gradlew packageDistributionForCurrentOS

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: distributions-${{ matrix.os }}
          path: |
            **/build/compose/binaries/**/*.msi
            **/build/compose/binaries/**/*.exe
            **/build/compose/binaries/**/*.deb
            **/build/compose/binaries/**/*.dmg
          if-no-files-found: ignore

  release:
    name: Create GitHub Release and Upload Artifacts
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/**/**/*.msi
            artifacts/**/**/*.exe
            artifacts/**/**/*.deb
            artifacts/**/**/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
